name: Build&UnitTest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: windows-latest  # For a list of available runner types, refer to 
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@2008f912f56e61277eefaac6d1888b750582aa16
      
    - name: Setup NuGet.exe
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: latest

    - name: Setup VSTest.console.exe
      uses: darenm/Setup-VSTest@v1
    
    - name: Setup inno
      uses: Amadevus/pwsh-script@v1.0.0
      with:
        # PowerShell script to execute in Actions-hydrated context
        script: (new-object net.webclient).DownloadFile('http://www.jrsoftware.org/download.php/is.exe#innosetup-6.0.3.exe', "$Env:APPVEYOR_BUILD_FOLDER/innosetup-6.0.3.exe") & $Env:APPVEYOR_BUILD_FOLDER/innosetup-6.0.3.exe /verysilent /norestart /currentuser 
        # 'github' workflow context
        #github: # optional, default is ${{ toJson(github) }}
        # 'job' workflow context
        #job: # optional, default is ${{ toJson(job) }}
        # 'runner' workflow context
        #runner: # optional, default is ${{ toJson(runner) }}
        # 'strategy' workflow context
        #strategy: # optional, default is ${{ toJson(strategy) }}
        # 'matrix' workflow context
        #matrix: # optional, default is ${{ toJson(matrix) }}
      
    - name: nuget restore
      run: nuget restore $Env:GITHUB_WORKSPACE\TaskManagement\TaskManagement.sln
      
    - name: MSBuild
      run: msbuild $Env:GITHUB_WORKSPACE\TaskManagement\TaskManagement.sln /property:Configuration=Release
    
    - name: VSTest
      run: VSTest.Console.exe UnitTestProject1\bin\Release\*Test*.dll
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
          name: artifacts
          path: TaskManagement\bin\Release\*
